title: OCCRP Commons
email: info@occrp.org
description: >-
  Investigative Dashboard (ID) is intended to help investigative journalists to
  do their work in a fast and effective way. It combines a number of software
  tools, including search engines, databases, a research support system and a
  file manager, to try to shorten the lead time from story inception to
  publication.
baseurl: ''
url: ''
logo: /static/svg/logo.svg
google_analytics: ''
repository_url: https://github.com/occrp/investigativedashboard.org

# Build settings
markdown: kramdown

sass:
  style: compressed

jekyll_get:
  # - data: collections
  #   json: 'https://data.occrp.org/api/2/collections?limit=0&facet=category&facet=countries'
  - data: aleph
    json: 'https://data.occrp.org/api/2/statistics'


autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-typogrify

exclude:
  - Gemfile
  - Gemfile.lock
